lab3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('web_rmpy.urls')),
    url(r'^admin/', admin.site.urls),
]

web_rmpy/urls.py
from django.conf.urls import url

from . import views

app_name = "web_rmpy"
urlpatterns = [
    url(r'^$', views.MainView.as_view(), name="bins"),
    url(r'^([0-9]+)/$', views.trash, name="trash"),
    url(r'^([0-9]+)/empty/$', views.empty, name="empty"),
    url(r'^([0-9]+)/regex/$', views.regex, name="regex"),
    url(r'^([0-9]+)/delete/$', views.delete, name="delete"),
    url(r'^([0-9]+)/recover/$', views.recover, name="recover"),
]

web_rmpy/models.py
from django.db import models


class Bin(models.Model):
    path = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.path


class Task(models.Model):
    action = models.CharField(max_length=40)
    object = models.CharField(max_length=100)
    status = models.CharField(max_length=20)
    bin = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.action + " " + "[" + self.status + "]"

web_rmpy/forms.py
from django import forms

from .validators import *


class DeleteForm(forms.Form):
    path = forms.CharField(max_length=100, validators=[validate_exist])

web_rmpy/views.py
import os

from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.views.generic import ListView
from django.views import View

from rmpy import rmpy

from .models import *
from .forms import *


def make_name(bin_path):
    trash_path = os.path.join(bin_path, "files")
    info_path = os.path.join(bin_path, "info")
    return trash_path, info_path


class MainView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "web_rmpy/index.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context["bins"] = Bin.objects.all()
        return context


def trash(request, bin_id):
    bin_path = Bin.objects.get(id=bin_id).path
    trash_path, _ = make_name(bin_path)
    trash_list = os.listdir(trash_path)
    context = {"dir": trash_list}
    return render(request, "web_rmpy/trash.html", context)


def recover(request, bin_id):
    bin_path = Bin.objects.get(id=bin_id).path
    trash_path, info_path = make_name(bin_path)
    elements = request.POST.getlist("elems")
    for element in elements:
        task = Task(action="Recover", object=element, status="In progress", bin=bin_path)
        task.save()
        rmpy.recover(element, trash_path, info_path)
        task.status = "OK"
        task.save()
    return HttpResponseRedirect("/" + bin_id)


def delete(request, bin_id):
    if not Task.objects.filter(action="Delete", status="In progress").exists():
        bin_path = Bin.objects.get(id=bin_id).path
        trash_path, info_path = make_name(bin_path)
        target = request.POST.get("target")
        task = Task(action="Delete", object=target, status="In progress", bin=bin_path)
        task.save()
        try:
            rmpy.remove_by_pattern(target, trash_path, info_path)
            task.status = "OK"
        except:
            task.status = "FAILED"
        finally:
            task.save()
        return HttpResponseRedirect("/" + bin_id)
    else:
        return HttpResponse("Error")


def empty(request, bin_id):
    bin_path = Bin.objects.get(id=bin_id).path
    trash_path, info_path = make_name(bin_path)
    task = Task(action="Empty", status="In progress", bin=bin_path)
    task.save()
    rmpy.empty_trash(trash_path, info_path)
    task.status = "OK"
    task.save()
    return HttpResponseRedirect("/" + bin_id)


def regex(request, bin_id):
    if not Task.objects.filter(action="Delete", status="In progress").exists():
        bin_path = Bin.objects.get(id=bin_id).path
        trash_path, info_path = make_name(bin_path)
        tree_path = request.POST.get("path")
        regexp = request.POST.get("regex")
        task = Task(action="Delete", object=regexp, status="In progress", bin=bin_path)
        task.save()
        try:
            rmpy.remove_by_regex(tree_path, regexp, trash_path, info_path)
            task.status = "OK"
        except:
            task.status = "FAILED"
        finally:
            task.save()
        return HttpResponseRedirect("/" + bin_id)
    else:
        return HttpResponse("Error")

web_rmpy/templates/web_rmpy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trash Bins</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style type="text/css">
        .step-links {
            text-align: center;
        }
        .add-bin {

        }
    </style>

</head>
<body>
    <div class="container">
        <h2>Trashes:</h2>

        <section class="bins">
            {% for bin in bins %}
                <a href="{% url "web_rmpy:trash" bin.id %}"><h4>{{ bin }}</h4></a> <br>
            {% endfor %}

            <a class="add-bin" href="/admin/web_rmpy/bin/add/"><h3>Add Bin</h3></a>
        </section>

        <section class="tasks">
            <h2>Tasks:</h2>
            {% for task in tasks %}
                {{ task }}<br />
            {% endfor %}

            <div class="step-links">
                {% if page_obj.has_previous %}
                    <a class="glyphicon glyphicon-arrow-left" href="?page={{ page_obj.previous_page_number }}"></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a class=" glyphicon glyphicon-arrow-right" href="?page={{ page_obj.next_page_number }}"></a>
                {% endif %}
            </div>
        </section>

    </div>
</body>
</html>

web_rmpy/templates/web_rmpy/trash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bin</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <a href="empty/"><h3>Empty trash</h3></a>

        <form action="delete/" method="POST">
            {% csrf_token %}
            <label for="target">File path: </label>
            <input id="target" type="text" name="target">
            <input type="submit" value="Delete">
        </form>

        <br>

        <form action="regex/" method="POST">
            {% csrf_token %}
            <label for="path">SubTree path: </label>
            <input id="path" type="text" name="path">
            <label for="regex">Regex: </label>
            <input id="regex" type="text" name="regex">
            <input type="submit" value="Delete by regex">
        </form>

        <form action="recover/" method="POST">
            {% csrf_token %}
            <h2>Trash Files:</h2>
            {% for elem in dir %}
                    <input type="checkbox" name="elems" value="{{ elem }}" />{{ elem }}<br>
            {% endfor %}
            <input type="submit" value="Recover">
        </form>
    </div>
</body>
</html>